{% set version = "2.6.4" %}

package:
  name: flex
  version: {{ version }}

source:
  url: https://github.com/westes/flex/releases/download/v{{ version }}/flex-{{ version }}.tar.gz
  sha256: e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995

build:
  number: 1005
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autotools_clang_conda  # [win]
    - automake  # [unix]
    - libtool   # [unix]
    - m4        # [unix]
    - make      # [unix]
    - libiconv  # [osx]
    - help2man  # [unix]
  run:
    - libiconv  # [osx]
    - m4        # [unix]

test:
  commands:
    # CLI tests
    - flex --help

    # header tests
    - test -f ${PREFIX}/include/FlexLexer.h         # [unix]
    - if not exist %LIBRARY_INC%\FlexLexer. exit 1  # [win]

    # Lib tests
    - test -f ${PREFIX}/lib/libfl.a                 # [unix]
    - test -f ${PREFIX}/lib/libfl${SHLIB_EXT}       # [unix]
    - if not exist %LIBRARY_LIB%\libfl.lib exit 1   # [win]

about:
  home: https://github.com/westes/flex
  license: BSD 2-Clause
  license_file: COPYING
  license_family: BSD
  summary: The Fast Lexical Analyzer
  dev_url: https://github.com/westes/flex

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
